# Generated by Django 4.1.2 on 2022-10-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marble', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marble',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
