# Generated by Django 4.1.2 on 2022-10-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marble', '0003_alter_marble_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='marble',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
