# Generated by Django 4.1.2 on 2022-10-28 16:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marble', '0006_alter_marble_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marble',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='marble',
            name='image',
            field=models.ImageField(upload_to='marbles'),
        ),
    ]
