# Generated by Django 4.1.2 on 2022-11-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marble', '0008_marble_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='marble',
            name='image_size',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
