# Generated by Django 4.1.2 on 2022-11-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marble', '0012_marble_image_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marble',
            name='image_size',
        ),
        migrations.AddField(
            model_name='marble',
            name='image_color',
            field=models.JSONField(null=True),
        ),
    ]
